version: '3'

services:
  express-app:
    build:
      context: .  # Build context is the current directory (where your Dockerfile is located)
      dockerfile: Dockerfile  # Use the specified Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'  